name = "Advanced Equipment"
prefix = "ae3"
author = "y0014984|Wasserstoff"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
files = [
    "mod.cpp",
    "README.md",
    "AUTHORS.txt",
    "LICENSE.md",
    "logo_ae3_ca.paa",
    "logo_ae3_ca_hover.paa",
    "logo_ae3_ca_font.paa",
    "meta.cpp"
]